#!/usr/bin/env bash
# LICENSE for this script is at the end of this file
#
# The launcher is designed to simplify the launch of Linux applications and move the home directory
# to avoid conflicts between different versions of the same application.

# Allows you to avoid configuration file conflicts when installing different versions of the same application.
ISHMoveHomeDir="true" # "true" / "false"
UseExtraLibs="false"
ISHTerminalPause="true"
MultiArch="true"

PathToScript="$( dirname "$(readlink -f "$0")")"; exit_code="0"

###########################################
## THESE VARIABLES NEED TO BE CONFIGURED ##
## ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ##
ProgramFolder="$PathToScript/program"          # Path to the program directory
ExeFolder="$ProgramFolder/bin"                 # Path to the directory with executable files
Executable="$ExeFolder/ExeFile"                # Main executable file
ExtraLibsFolder64="$PathToScript/libs64"       # Extra libraries
ExtraLibsFolder32="$PathToScript/libs32"       # Extra libraries for 32-bit OS
ExtraLibsArch="x64"                            # Default extra libraries arch...
DefaultUserDataFolder="$PathToScript/userdata" # Default path to the User Data
UserDataFolder="$DefaultUserDataFolder"

if [ "$MultiArch" == "true" ]; then
	OS=$(uname -s)
	ARCH=$(uname -m)

	case "${OS}_${ARCH}" in
		Linux_x86_64)   Executable="$ExeFolder/ExeFile-lin64"; ExtraLibsArch="x64" ;;
		Linux_aarch64)  Executable="$ExeFolder/ExeFile-armlin64"; ExtraLibsArch="x64" ;;
		Linux_i686|Linux_i586|Linux_i486|Linux_i386) Executable="$ExeFolder/ExeFile-lin32"; ExtraLibsArch="x32" ;;
		Linux_armv7l|Linux_armv6l) Executable="$ExeFolder/ExeFile-armlin32"; ExtraLibsArch="x32" ;;
		
		FreeBSD_amd64)  Executable="$ExeFolder/ExeFile-bsd64"; ExtraLibsArch="x64" ;;
		FreeBSD_arm64)  Executable="$ExeFolder/ExeFile-armbsd64"; ExtraLibsArch="x64" ;;
		FreeBSD_i386)   Executable="$ExeFolder/ExeFile-bsd32"; ExtraLibsArch="x32" ;;
		FreeBSD_arm*)   Executable="$ExeFolder/ExeFile-armbsd32"; ExtraLibsArch="x32" ;;
		
		*) echo "ISH Error: The ${OS} ${ARCH} architecture is not supported"; exit_code="The ${OS} ${ARCH} architecture is not supported" ;;
	esac
fi

################################################
## Space for additional variables and actions ##
#export SOME_IMPORTANT_VARIABLE="example"

#################################################
## DO NOT TOUCH THIS WITHOUT A SERIOUS REASON! ##
if [ -e "$PathToScript/ish-settings" ]; then
	source "$PathToScript/ish-settings" ## IMPORT SETTINGS 
fi

if [ -z "$ISHPogramArch" ]; then ISHPogramArch="other"; fi # CHECKING IMPORTED VARIABLES
if [ -z "$ISHProgramFName" ]; then ISHProgramFName="other"; fi
if [ -z "$ISHInstallPathUser" ]; then ISHInstallPathUser="$HOME/portsoft"; fi
if [ -z "$ISHInstallPathSystem" ]; then ISHInstallPathSystem="/portsoft"; fi
if [ -z "$ISHInstallPathUserFull" ]; then ISHInstallPathUserFull="$ISHInstallPathUser/$ISHPogramArch/$ISHProgramFName"; fi
if [ -z "$ISHInstallPathSystemFull" ]; then ISHInstallPathSystemFull="$ISHInstallPathSystem/$ISHPogramArch/$ISHProgramFName"; fi
# Checks if the program is installed in system mode, and if so, uses the user's home directory to store data and configurations.
if [ "$PathToScript" == "$ISHInstallPathSystemFull" ]; then
	ish_path_rights="true"
	if [ ! -e "$ISHInstallPathUserFull" ]; then
		if ! mkdir -p "$ISHInstallPathUserFull"; then echo "No_Rights"; ish_path_rights="false"; fi
		if [ "$ish_path_rights" == "true" ]; then cp -rf "$ISHInstallPathSystemFull/userdata/". "$ISHInstallPathUserFull/userdata"; fi
	fi
	UserDataFolder="$ISHInstallPathUserFull/userdata"
elif [ "$PathToScript" == "$ISHInstallPathUserFull" ]; then
	UserDataFolder="$ISHInstallPathUserFull/userdata"
fi

export PATH="$ExeFolder:$PATH" # Use ":" for separation

if [ "$ISHMoveHomeDir" == "true" ]; then
	export HOME="$UserDataFolder"
	export HOMECONFIGS="$UserDataFolder"
	#export XDG_DATA_DIRS="$HOMECONFIGS/.local/share:$XDG_DATA_DIRS"
	export XDG_DATA_HOME="$HOMECONFIGS/.local/share"
	export XDG_STATE_HOME="$HOMECONFIGS/.local/state"
	export XDG_CONFIG_HOME="$HOMECONFIGS/.config"
	export XDG_CACHE_HOME="$HOMECONFIGS/.cache"
fi

if [ "$UseExtraLibs" == "true" ]; then
	
	if [ "$ExtraLibsArch" == "x64" ]; then
		if [ -z "$LD_LIBRARY_PATH" ]; then
			export LD_LIBRARY_PATH="$ExtraLibsFolder64"
		else
			export LD_LIBRARY_PATH="$ExtraLibsFolder64:$LD_LIBRARY_PATH" # Use ":" for separation
		fi
	
		if [ "$MultiArch" == "true" ]; then
			export LD_32_LIBRARY_PATH="$LD_LIBRARY_PATH"
			export LD_64_LIBRARY_PATH="$LD_LIBRARY_PATH"
		fi
	fi
	
	if [ "$ExtraLibsArch" == "x32" ]; then
		if [ -z "$LD_LIBRARY_PATH" ]; then
			export LD_LIBRARY_PATH="$ExtraLibsFolder32"
		else
			export LD_LIBRARY_PATH="$ExtraLibsFolder32:$LD_LIBRARY_PATH" # Use ":" for separation
		fi
	
		if [ "$MultiArch" == "true" ]; then export LD_32_LIBRARY_PATH="$LD_LIBRARY_PATH"; fi
	fi
	
fi

if [ -e "$Executable" ]; then
	if [ ! -x "$Executable" ]; then if ! chmod +x "$Executable"; then echo "chmod error"; fi; fi
	cd "$ExeFolder" || exit
	"$Executable" "$@"
	exit_code="$?"
else
	exit_code="Executable not found... - $exit_code"
fi

if [ "$exit_code" != "0" ]; then
	StringMessage="bash -c 'echo \"-\"; echo \"$Executable\"; echo \"-\"; echo \"WARNING! EXIT CODE - $exit_code\"; echo \"The program has terminated incorrectly!\"; echo \"Is the program incompatible with the current OS?\"; echo \"Does the program contain errors?\"; read pause'"
	
	export PATH="/usr/local/bin:/usr/bin:/bin:$PATH"
	export LD_LIBRARY_PATH=""
	
	terminal_executable="x-terminal-emulator"
	if ! type "x-terminal-emulator" &> /dev/null; then
		if type "xfce4-terminal" &> /dev/null; then terminal_executable="xfce4-terminal"
		elif type "konsole" &> /dev/null; then terminal_executable="konsole"
		elif type "gnome-terminal" &> /dev/null; then terminal_executable="gnome-terminal"
		elif type "xterm" &> /dev/null; then terminal_executable="xterm"
		elif type "uxterm" &> /dev/null; then terminal_executable="uxterm"; fi
	fi
	
	$terminal_executable -e "$StringMessage"
fi

if [ "$ISHTerminalPause" == "true" ]; then read -r pause; fi

# MIT License
#
# Copyright (c) 2025-2026 Андрей Цымбалов (Chimbal)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
