#!/usr/bin/env bash
# Script version 1.0

Args=("$@")

echo -e "Example Application!\n"

echo -e "HOME: $HOME\n"
echo -e "XDG_DATA_HOME: $XDG_DATA_HOME\n"
echo -e "XDG_STATE_HOME: $XDG_STATE_HOME\n"
echo -e "XDG_CONFIG_HOME: $XDG_CONFIG_HOME\n"
echo -e "XDG_CACHE_HOME: $XDG_CACHE_HOME\n"
echo -e "PWD: $PWD\n"
echo -e "PATH: $PATH\n"
echo -e "LD_LIBRARY_PATH: $LD_LIBRARY_PATH\n"

for i in "${!Args[@]}"; do
	echo -e "${Args[$i]}"
done

read pause
